import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLinkedin, faGithub } from "@fortawesome/free-brands-svg-icons";

const About = () => {
  return (
    <div className="glassmorphism">
      <h1 className="text-center">About Us</h1>
      <div className="flex mt-[10%] mx-[15%] glassmorphism border-t border-white/50 border-r-0 px-12 py-8 rounded-[20px] max-[720px]:flex-col max-[720px]:mt-[10%] max-[720px]:items-center">
        <img
          className="w-60 h-60 rounded-full ml-[60px] max-[720px]:ml-0 max-[720px]:h-25 max-[720px]:w-25 max-[720px]:mt-5"
          alt="profile"
          src="Images/profile.jpeg"
        ></img>
        <div className="flex flex-col mt-[5%] ml-[10%] max-[720px]:m-[15%_0_15%_0] max-[720px]:text-center max-[720px]:w-full">
          <h2 className="cursor-default hover:skew-x-[-15deg]">M. Srinivas</h2>
          <h4 className="mt-[5%] text-hover">
            Competitive Coder | Full Stack Developer
          </h4>
          <h3 className="mt-[5%]">Find me on</h3>
          <div className="flex mt-[10%] max-[720px]:text-center max-[720px]:mt-[10%] max-[720px]:ml-[35%] max-[720px]:p-[2%]">
            <a
              href="https://www.linkedin.com/in/srinivas-m-298764191/"
              target="_blank"
              rel="noreferrer"
              className="ml-[0.5%] max-[720px]:mr-[10%]"
            >
              <FontAwesomeIcon
                className="cursor-pointer animate-[pulse_0.8s_ease-in-out_infinite_alternate]"
                icon={faLinkedin}
              />
            </a>
            <a
              href="https://github.com/coder-srinivas"
              target="_blank"
              rel="noreferrer"
              className="ml-[10%]"
            >
              <FontAwesomeIcon
                className="cursor-pointer animate-[pulse_0.8s_ease-in-out_infinite_alternate]"
                icon={faGithub}
              />
            </a>
          </div>
        </div>
      </div>
      <div className="flex flex-col text-center mt-[10%]">
        <h1 className="text-hover">What is the IPL auction?</h1>
        <p className="m-[5%]">
          It began back during my childhood days, the urge to play the IPL
          Auction depicting real players. I used to team up with my friends and
          play the auction manually with a pen and paper, with a organizer to
          keep track. Over the last 1 year, I wondered, can I do anything to
          make my experience better? So I came up with the idea of building a
          IPL auction app, based on the MERN stack. You can team up with your
          friends and dive into the fun world of auctioning IPL players. The
          application calculates the score generated by each team based on the
          performance of each player in the respective IPL year. The team with
          the most points wins. It's a fun application to experience the the
          real IPL Auction with friends. Simply create an account, gather your
          friends and jump straight into the auction.
        </p>
      </div>
    </div>
  );
};

export default About;
